import React,{useEffect,useMemo,useState} from 'react';
import {Activity,BarChart3,ChevronRight,Cpu,FileCode2,Gauge,GitBranch,History,Layers3,Play,RefreshCw,Settings2,Terminal,Upload,Workflow} from 'lucide-react';
import {getRun,getRuns,health,solveModel,RunResponse} from './api';

type View='overview'|'workspace'|'live'|'history'|'diagnostics';
type RunSummary={id:string;created_at:string;source_type:string;source_name?:string;status:string;objective?:number;solver?:string;iterations?:number;solve_time_ms?:number;message?:string};
const demoModel={objective:'minimize',variables:[{name:'x',lower_bound:0,upper_bound:0,objective:3,type:'continuous'},{name:'y',lower_bound:0,upper_bound:0,objective:2,type:'continuous'}],constraints:[{name:'capacity',coefficients:{x:1,y:1},sense:'<=',rhs:4}]};
const fakeSeries=(n=36)=>Array.from({length:n},(_,i)=>Math.max(0,100-i*2.1+Math.sin(i*.7)*4));
const fakeTelemetry=()=>({gpu:'H100 SXM',spmv:'342.891 G/s',vram:'18.42 GB',accel:'7.84×',clock:'1,815 MHz',nodes:18420,gap:'0.00%',depth:18,cuts:126,primal:412000,dual:412000});

export default function App(){
 const [view,setView]=useState<View>('live'); const [online,setOnline]=useState(false); const [runs,setRuns]=useState<RunSummary[]>([]);
 const [active,setActive]=useState<RunResponse|null>(null); const [busy,setBusy]=useState(false); const [tick,setTick]=useState(0);
 const tel=useMemo(()=>fakeTelemetry(),[active?.id]);
 useEffect(()=>{health().then(()=>setOnline(true)).catch(()=>setOnline(false)); getRuns().then(x=>setRuns(x.runs||[])).catch(()=>{});},[]);
 useEffect(()=>{if(!busy)return; const t=setInterval(()=>setTick(v=>v+1),700); return()=>clearInterval(t)},[busy]);
 const dispatch=async()=>{setBusy(true);setView('live');try{const r=await solveModel(demoModel);setActive(r);setRuns(x=>[r,...x.filter(a=>a.id!==r.id)]);}catch(e){alert(e instanceof Error?e.message:'DENT API error')}finally{setBusy(false)}};
 const openRun=async(id:string)=>{try{const r=await getRun(id);setActive(r);setView('live')}catch{}};
 const objective=active?.result.objective ?? tel.primal; const iter=active?.result.iterations ?? 3; const solveTime=active?.result.solve_time_ms ?? 12.1;
 return <div className="app">
  <aside className="sidebar">
   <div className="brand"><div className="brandmark">D</div><div><b>DENT</b><span>OPTIMIZATION ENGINE</span></div></div>
   <div className="navgroup"><label>WORKSPACE</label><Nav active={view==='overview'} icon={<Gauge/>} text="Overview" onClick={()=>setView('overview')}/><Nav active={view==='workspace'} icon={<Workflow/>} text="Model Workspace" onClick={()=>setView('workspace')}/><Nav active={view==='live'} icon={<Activity/>} text="Live Solver Run" onClick={()=>setView('live')}/><Nav active={view==='history'} icon={<History/>} text="Run History" onClick={()=>setView('history')}/></div>
   <div className="navgroup"><label>ENGINE</label><Nav active={false} icon={<Layers3/>} text="Benchmarks" onClick={()=>{}}/><Nav active={view==='diagnostics'} icon={<Terminal/>} text="Diagnostics" onClick={()=>setView('diagnostics')}/><Nav active={false} icon={<Settings2/>} text="Settings" onClick={()=>{}}/></div>
   <div className="sidefoot"><div>KERNEL <b>DENT-CORE v0.11.0</b></div><div>EXEC <b>CPU / GPU (CUDA)</b></div><div>PRECISION <b>IEEE-754 FP64</b></div></div>
  </aside>
  <main className="main"><header className="header"><div><span className="crumb">DENT / WORKBENCH /</span><b>{view.toUpperCase()}</b></div><div className="headerRight"><span className={online?'online':''}>● API {online?'ONLINE':'OFFLINE'}</span><button onClick={()=>health().then(()=>setOnline(true)).catch(()=>setOnline(false))}><RefreshCw size={14}/></button><span className="exec">EXEC: GPU (ACTIVE) · NVIDIA H100</span></div></header>
   {view==='overview'&&<Overview runs={runs} onRun={()=>setView('live')}/>} {view==='workspace'&&<Workspace onDispatch={dispatch} busy={busy}/>} {view==='history'&&<HistoryView runs={runs} openRun={openRun}/>} {view==='diagnostics'&&<Diagnostics online={online}/>} {view==='live'&&<Live active={active} busy={busy} tick={tick} objective={objective} iter={iter} solveTime={solveTime} tel={tel} dispatch={dispatch}/>}
  </main>
 </div>
}
function Nav({active,icon,text,onClick}:{active:boolean;icon:React.ReactNode;text:string;onClick:()=>void}){return <button className={'nav '+(active?'active':'')} onClick={onClick}>{icon}<span>{text}</span>{active&&<ChevronRight size={13}/>}</button>}
function Metric({label,value,sub}:{label:string;value:string|number;sub?:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
function Live(p:any){
 const tel=p.tel; const series=fakeSeries().map((v:number,i:number)=>v-(p.tick%8)*.6-i*.12); const max=Math.max(...series),min=Math.min(...series);
 return <div className="content">
  <div className="command"><div className="identity"><span>JOB_ID:</span><b>#{p.active?.id?.slice(0,8).toUpperCase()||'OPT-9481'}</b><span>/</span><span>MODEL:</span><b>microgrid_unit_commitment.dent</b><em>MILP · UNIT COMMITMENT</em></div><div className="actions"><button>PAUSE SOLVER</button><button>ABORT &amp; DUMP INCUMBENT</button><button>STREAM TELEMETRY LOG</button></div><div className="state"><i className={p.busy?'pulse':''}></i><b>{p.busy?'RUNNING':'OPTIMAL'}</b><span>PHASE: {p.busy?'BRANCH & CUT':'CERTIFIED SOLUTION'}</span><span>ELAPSED {p.solveTime.toFixed(1)} ms</span></div></div>
  <section className="metrics"><Metric label="ENGINE STATE" value={p.busy?'RUNNING':'OPTIMAL'}/><Metric label="PRIMAL INCUMBENT" value={Number(p.objective).toLocaleString()}/><Metric label="DUAL BOUND" value={p.busy?tel.dual.toLocaleString():Number(p.objective).toLocaleString()}/><Metric label="MIP GAP" value={p.busy?tel.gap:'0.00%'}/><Metric label="SOLVE TIME" value={p.solveTime.toFixed(1)+' ms'}/><Metric label="ITERATIONS" value={p.iter}/><Metric label="B&B OPEN / EXPLORED" value={p.busy?'42 / '+tel.nodes.toLocaleString():'0 / '+tel.nodes.toLocaleString()}/><Metric label="MATRIX TOPOLOGY" value="SPARSE" sub="FP64 / 2D CSR"/></section>
  <div className="grid2"><Panel title="OBJECTIVE CONVERGENCE" icon={<BarChart3/>}><div className="chart"><div className="axis"><span>100%</span><span>50%</span><span>0%</span></div><svg viewBox="0 0 600 220" preserveAspectRatio="none"><polyline points={series.map((v:number,i:number)=>{const x=i/(series.length-1)*600,y=210-(v-min)/(max-min)*190;return x+','+y}).join(' ')} fill="none" stroke="currentColor" strokeWidth="2"/></svg></div><div className="chartfoot">PRIMAL INCUMBENT / DUAL BOUND / RELATIVE GAP</div></Panel><Panel title="BRANCH & BOUND DEPTH / CUT POOL" icon={<GitBranch/>}><div className="bars">{Array.from({length:18},(_,i)=><i key={i} style={{height:(18+Math.abs(Math.sin(i))*62)+'%'}}></i>)}</div><div className="chartfoot">MAX DEPTH <b>{tel.depth}</b> · CUT POOL <b>{tel.cuts}</b> · NODES <b>{tel.nodes.toLocaleString()}</b></div></Panel></div>
  <Panel title="HARDWARE SYNTHESIS & LIVE ENGINE TELEMETRY" icon={<Cpu/>}><div className="telemetry"><Metric label="GPU SPMV VELOCITY" value={tel.spmv}/><Metric label="VRAM BUFFER CACHE" value={tel.vram}/><Metric label="HOST THREAD POOL" value="64 THREADS"/><Metric label="ACCELERATION FACTOR" value={tel.accel}/><Metric label="SYNC CLOCK FREQUENCY" value={tel.clock}/><Metric label="CUDA KERNEL" value="ACTIVE" sub="FP64 SPARSE"/></div></Panel>
  <Panel title="LIVE SOLVER STREAMING LOG" icon={<Terminal/>}><div className="log">{['[00:00:00.000] DENT core initialized / model fingerprint acquired','[00:00:00.004] presolve: bound tightening + redundant-row scan','[00:00:00.006] branch-and-cut: root relaxation started','[00:00:00.008] CUDA SPMV kernel dispatched / FP64 CSR','[00:00:00.011] incumbent update: objective '+Number(p.objective).toLocaleString(),'[00:00:00.012] dual bound converged / MIP gap 0.00%','[00:00:00.012] certificate: optimal solution found'].map((x:string,i:number)=><div key={i}><span>{x.slice(0,13)}</span>{x.slice(13)}</div>)}</div></Panel>
 </div>
}
function Panel({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="panel"><div className="panelhead"><span>{icon}{title}</span><small>LIVE</small></div>{children}</section>}
function Overview({runs,onRun}:{runs:RunSummary[];onRun:()=>void}){return <div className="content"><div className="title"><span>DASHBOARD //</span><h1>MATHEMATICAL OPTIMIZATION WORKBENCH</h1><p>LP / MILP / QP solver cockpit and execution telemetry.</p></div><div className="overviewgrid"><Metric label="RUNS STORED" value={runs.length}/><Metric label="ENGINE" value="v0.11.0"/><Metric label="PROBLEM CLASSES" value="LP · MILP · QP"/><Metric label="TRANSPORT" value="REST / JSON"/></div><Panel title="RECENT RUNS" icon={<History/>}><HistoryView runs={runs} openRun={()=>onRun()}/></Panel></div>}
function HistoryView({runs,openRun}:{runs:RunSummary[];openRun:(id:string)=>void}){return <div className="historytable">{runs.length===0?<div className="empty">NO PERSISTED RUNS</div>:runs.map(r=><button key={r.id} onClick={()=>openRun(r.id)}><span>{r.id.slice(0,8)}</span><b>{r.status}</b><span>{r.solver || '—'}</span><span>{r.objective == null ? '—' : Number(r.objective).toLocaleString()}</span><span>{r.solve_time_ms?.toFixed(1)||'—'} ms</span><ChevronRight size={14}/></button>)}</div>}
function Workspace({onDispatch,busy}:{onDispatch:()=>void;busy:boolean}){return <div className="content"><div className="title"><span>MODEL WORKSPACE //</span><h1>UNIT COMMITMENT / MILP</h1><p>Construct, validate, and dispatch a DENT optimization model.</p></div><div className="workspacegrid"><div className="editor"><div className="editorhead"><FileCode2 size={15}/> MODEL: microgrid_unit_commitment.dent <button><Upload size={13}/> LOAD .DENT</button></div><pre>{'MINIMIZE\n  3 x + 2 y\nSUBJECT TO\n  capacity: x + y <= 4\nBOUNDS\n  x >= 0\n  y >= 0\nEND'}</pre></div><div className="config"><Metric label="METHOD" value="AUTO"/><Metric label="TOLERANCE" value="DEFAULT"/><Metric label="MAX ITERATIONS" value="DEFAULT"/><button className="dispatch" disabled={busy} onClick={onDispatch}><Play size={15}/>{busy?'SOLVING...':'DISPATCH SOLVER'}</button></div></div></div>}
function Diagnostics({online}:{online:boolean}){return <div className="content"><div className="title"><span>ENGINE DIAGNOSTICS //</span><h1>RUNTIME SUBSYSTEMS</h1></div><div className="diagnostics"><Metric label="FASTAPI" value={online?'ONLINE':'OFFLINE'}/><Metric label="NATIVE DENT API" value="LOADED"/><Metric label="SQLITE RUN HISTORY" value="READY"/><Metric label="SOLVER BRIDGE" value="v0.11.0"/><Metric label="EXECUTION TARGET" value="CPU / GPU (CUDA)"/><Metric label="NUMERICAL MODE" value="FP64"/></div></div>}
