#pragma once

#if defined(_WIN32)

    #if defined(DENT_BUILDING_DLL)
        #define DENT_API __declspec(dllexport)
    #else
        #define DENT_API __declspec(dllimport)
    #endif

#else

    #if defined(DENT_BUILDING_DLL)
        #define DENT_API __attribute__((visibility("default")))
    #else
        #define DENT_API
    #endif

#endif


#ifdef __cplusplus
extern "C" {
#endif


/*
 * ============================================================
 * DENT C API
 * ============================================================
 *
 * The API intentionally exposes only C-compatible types.
 *
 * C++ implementation objects are represented by opaque handles.
 */


/*
 * Opaque model handle.
 *
 * The implementation owns the actual C++ dent::Problem object.
 */
typedef struct dent_model_t dent_model_t;


/*
 * Variable types.
 */
enum dent_variable_type
{
    DENT_VARIABLE_CONTINUOUS = 0,
    DENT_VARIABLE_INTEGER = 1,
    DENT_VARIABLE_BINARY = 2
};


/*
 * Constraint senses.
 */
enum dent_constraint_sense
{
    DENT_CONSTRAINT_LESS_EQUAL = 0,
    DENT_CONSTRAINT_EQUAL = 1,
    DENT_CONSTRAINT_GREATER_EQUAL = 2
};


/*
 * Solver methods.
 *
 * DENT_SOLVER_AUTO delegates solver selection to the adaptive
 * dispatcher. The remaining values request a specific exposed
 * solver implementation.
 */
enum dent_solver_method
{
    DENT_SOLVER_AUTO = 0,
    DENT_SOLVER_PRIMAL_SIMPLEX = 1,
    DENT_SOLVER_DUAL_SIMPLEX = 2,
    DENT_SOLVER_INTERIOR_POINT = 3,
    DENT_SOLVER_PDHG = 4,
    DENT_SOLVER_PDLP = 5,
    DENT_SOLVER_QP = 6,
    DENT_SOLVER_MILP = 7,
    DENT_SOLVER_MIQP = 8
};


/*
 * Create an empty optimization model.
 *
 * maximize:
 *     non-zero -> maximize
 *     zero     -> minimize
 *
 * Returns nullptr on failure.
 */
DENT_API dent_model_t* dent_model_create(
    int maximize
);


/*
 * Parse an existing .dent model file into a model handle.
 *
 * Returns nullptr on failure.
 */
DENT_API dent_model_t* dent_model_create_from_file(
    const char* model_path
);


/*
 * Destroy a model handle.
 */
DENT_API void dent_model_destroy(
    dent_model_t* model
);


/*
 * Add a variable.
 *
 * upper_bound == 0 means +infinity, matching the current
 * DENT Problem representation.
 *
 * Returns the zero-based variable index.
 * Returns -1 on failure.
 */
DENT_API int dent_model_add_variable(
    dent_model_t* model,
    const char* name,
    double lower_bound,
    double upper_bound,
    int variable_type
);


/*
 * Add a linear constraint.
 *
 * Returns the zero-based constraint index.
 * Returns -1 on failure.
 */
DENT_API int dent_model_add_constraint(
    dent_model_t* model,
    const char* name,
    int constraint_sense,
    double rhs
);


/*
 * Set a linear objective coefficient.
 */
DENT_API int dent_model_set_objective_coefficient(
    dent_model_t* model,
    int variable,
    double coefficient
);


/*
 * Set a linear constraint coefficient.
 */
DENT_API int dent_model_set_constraint_coefficient(
    dent_model_t* model,
    int constraint,
    int variable,
    double coefficient
);


/*
 * Set a quadratic objective coefficient.
 *
 * DENT represents the quadratic objective as:
 *
 *     1/2 x^T Q x + c^T x
 */
DENT_API int dent_model_set_quadratic_coefficient(
    dent_model_t* model,
    int row_variable,
    int column_variable,
    double coefficient
);


/*
 * Change a variable type.
 */
DENT_API int dent_model_set_variable_type(
    dent_model_t* model,
    int variable,
    int variable_type
);


/*
 * Change variable bounds.
 *
 * upper_bound == 0 means +infinity.
 */
DENT_API int dent_model_set_variable_bounds(
    dent_model_t* model,
    int variable,
    double lower_bound,
    double upper_bound
);


/*
 * Solve an in-memory model and return its result as JSON.
 *
 * The returned string is allocated by DENT and must be released
 * using dent_free_string().
 *
 * Returns nullptr on failure.
 */
DENT_API const char* dent_model_solve_json(
    const dent_model_t* model
);


/*
 * Solve an in-memory model with explicit solver options.
 *
 * solver_method:
 *     one of dent_solver_method.
 *
 * tolerance:
 *     positive numerical tolerance.
 *
 * max_iterations:
 *     positive iteration/node limit. A value <= 0 uses the
 *     solver's built-in default.
 */
DENT_API const char* dent_model_solve_json_with_options(
    const dent_model_t* model,
    int solver_method,
    double tolerance,
    int max_iterations
);


/*
 * Solve a .dent model file and return its result as JSON.
 *
 * The returned string is allocated by DENT and must be released
 * using dent_free_string().
 *
 * Returns nullptr on failure.
 */
DENT_API const char* dent_solve_file_json(
    const char* model_path
);


/*
 * Solve a .dent model file with explicit solver options.
 */
DENT_API const char* dent_solve_file_json_with_options(
    const char* model_path,
    int solver_method,
    double tolerance,
    int max_iterations
);


/*
 * Retrieve the most recent error generated by the calling thread.
 *
 * The returned pointer is owned by DENT and must not be freed.
 *
 * The message remains valid until another DENT API call on the
 * same thread changes it.
 */
DENT_API const char* dent_last_error(
    void
);


/*
 * Free a string returned by DENT.
 */
DENT_API void dent_free_string(
    const char* value
);


#ifdef __cplusplus
}
#endif