import {useEffect,useMemo,useState} from "react";
import type {ReactNode} from "react";
import {ChevronDown,CircleCheck,Play,RefreshCw,Trash2} from "lucide-react";
import {getHealth,getRuns,solveFile,solveModel} from "./api";
import {sampleModel} from "./sampleModel";
import ModelInputPage from "./ModelInputPage";
import type {RunResponse,RunSummary,SolveRequest,SolverMethod} from "./types";

const labels:Record<SolverMethod,string>={auto:"AUTO",primal_simplex:"PRIMAL SIMPLEX",interior_point:"INTERIOR POINT",pdhg:"PDHG",pdlp:"PDLP",qp:"QP",milp:"MILP"};
const stages=["MODEL","PRESOLVE","STRATEGY","SOLVE","SOLUTION","CERTIFICATE"] as const;
type Stage=typeof stages[number];
type View="workbench"|"history"|"model"|"input"|"benchmarks";
type Iteration={iter:number;objective:number;step:number;primal:number;dual:number;gap:number};
type TelemetryState={iterations:Iteration[];presolveMs:number;strategyMs:number;solveMs:number;postsolveMs:number;certificateMs:number;nodes:number;cuts:number;selected:string;confidence:number;phase:string};

const problems=[
 {name:"refinery_blending_lp",kind:"LP",vars:15,cons:14,nnz:59,method:"INTERIOR POINT"},
 {name:"supply_chain_lp",kind:"LP",vars:50,cons:42,nnz:188,method:"PDLP"},
 {name:"supply_chain_lp_50k",kind:"LP",vars:50000,cons:42000,nnz:188000,method:"PDLP"},
 {name:"power_unit_commitment",kind:"MILP",vars:128,cons:96,nnz:742,method:"MILP"},
 {name:"power_unit_commitment_large",kind:"MILP",vars:10000,cons:8200,nnz:64000,method:"MILP"},
 {name:"unit_commitment_fleet",kind:"MILP",vars:3200,cons:1900,nnz:18400,method:"MILP"},
 {name:"facility_location_1220",kind:"MILP",vars:1220,cons:610,nnz:7200,method:"MILP"},
 {name:"portfolio_miqp",kind:"MIQP",vars:80,cons:34,nnz:530,method:"QP"}
];
const library=[
 {group:"lp",items:["netlib_afiro","refinery_blending_lp","supply_chain_lp","supply_chain_lp_50k"]},
 {group:"qp",items:["refinery_blending_qp"]},
 {group:"milp",items:["power_unit_commitment","power_unit_commitment_large","unit_commitment_fleet","facility_location_1220"]},
 {group:"miqp",items:["portfolio_miqp"]}
];

export default function App(){
 const [model,setModel]=useState<SolveRequest>(sampleModel);
 const [run,setRun]=useState<RunResponse|null>(null);
 const [runs,setRuns]=useState<RunSummary[]>([]);
 const [online,setOnline]=useState(false);
 const [running,setRunning]=useState(false);
 const [view,setView]=useState<View>("workbench");
 const [stage,setStage]=useState<Stage>("MODEL");
 const [selectedProblem,setSelectedProblem]=useState("refinery_blending_lp");
 const [error,setError]=useState("");
 const [telemetry,setTelemetry]=useState<TelemetryState>(makeTelemetry(15,"INTERIOR POINT"));
 const [now,setNow]=useState(0);
 const refresh=async()=>{try{const pair=await Promise.all([getHealth(),getRuns()]);setOnline(pair[0].native_api);setRuns(pair[1].runs)}catch{setOnline(false)}};
 useEffect(()=>{void refresh()},[]);
 useEffect(()=>{if(!running)return;const id=window.setInterval(()=>setNow(v=>v+100),100);return()=>window.clearInterval(id)},[running]);
 const execute=async(nextModel=model)=>{
  setRunning(true);setError("");setRun(null);setStage("MODEL");setNow(0);
  try{
   setStage("PRESOLVE");await delay(420);
   setStage("STRATEGY");await delay(420);
   setModel(nextModel);
   const r=await solveModel(nextModel);setRun(r);
   const selected=r.result.solver||labels[model.solver.method];
   const count=Math.max(8,Math.min(40,r.result.iterations||15));
   setTelemetry(makeTelemetry(count,selected,r.result.objective));
   setStage("SOLVE");await delay(Math.min(3200,Math.max(1400,count*85)));
   setStage("SOLUTION");await delay(650);setStage("CERTIFICATE");await delay(650);await refresh();
  }catch(e){setError(e instanceof Error?e.message:"Solver request failed.");setStage("MODEL")}
  finally{setRunning(false)}
 };
 const executeFile=async(file:File)=>{
  setRunning(true);setError("");setRun(null);setStage("MODEL");setNow(0);
  try{const r=await solveFile(file,{method:"auto",tolerance:0,max_iterations:0});setRun(r);setTelemetry(makeTelemetry(Math.max(8,Math.min(40,r.result.iterations||15)),r.result.solver,r.result.objective));setStage("SOLUTION");await refresh()}catch(e){setError(e instanceof Error?e.message:"File solve failed.");setStage("MODEL")}finally{setRunning(false)}
 };
 const selected=problems.find(p=>p.name===selectedProblem)||problems[0];
 return <div className="app-shell">
  <header className="workbar"><div className="brandline"><span className="brandword">sovereign</span><span className="version">v2.0.0</span><span>|</span></div><nav><button className={view==="workbench"?"topnav active":"topnav"} onClick={()=>setView("workbench")}>workbench</button><button className={view==="input"?"topnav active":"topnav"} onClick={()=>setView("input")}>model input</button><button className={view==="benchmarks"?"topnav active":"topnav"} onClick={()=>setView("benchmarks")}>benchmarks</button><button className={online?"topnav api-online":"topnav"}><i/>api {online?"online":"offline"} <span>http://localhost:8000</span></button></nav><div className="hardware">12 cores · cpu</div></header>
  {view==="workbench"&&<Workbench model={model} setModel={setModel} run={run} running={running} online={online} stage={stage} setStage={setStage} telemetry={telemetry} selectedProblem={selectedProblem} setSelectedProblem={setSelectedProblem} execute={execute} error={error} now={now} onHistory={()=>setView("history")} onModel={()=>setView("model")} selected={selected}/>}
  {view==="history"&&<HistoryView runs={runs} onBack={()=>setView("workbench")} onRefresh={()=>void refresh()}/>}
  {view==="model"&&<ModelPage model={model} setModel={setModel} onBack={()=>setView("workbench")}/>}
  {view==="input"&&<ModelInputPage model={model} setModel={setModel} running={running} onRun={execute} onFileRun={executeFile} onBack={()=>setView("workbench")}/>}
  {view==="benchmarks"&&<BenchmarkPage onBack={()=>setView("workbench")}/>}
 </div>
}

function Workbench(p:{model:SolveRequest;setModel:(m:SolveRequest)=>void;run:RunResponse|null;running:boolean;online:boolean;stage:Stage;setStage:(s:Stage)=>void;telemetry:TelemetryState;selectedProblem:string;setSelectedProblem:(s:string)=>void;execute:()=>Promise<void>;error:string;now:number;onHistory:()=>void;onModel:()=>void;selected:{name:string;kind:string;vars:number;cons:number;nnz:number;method:string}}){
 const result=p.run?.result;
 return <main className="workbench"><aside className="problem-rail"><div className="rail-title">problems <span>↕</span></div>{library.map(group=><div className="problem-group" key={group.group}><div className="group-label"># {group.group}</div>{group.items.map(name=><button key={name} className={p.selectedProblem===name?"problem active":"problem"} onClick={()=>{p.setSelectedProblem(name);p.setStage("MODEL")}}><span>{p.selectedProblem===name?">":" "}</span>{name}</button>)}</div>)}<div className="rail-divider"/><div className="group-label gold">public benchmark library</div><button className="problem"># netlib lp</button><button className="problem indent">afiro</button><div className="rail-help">[open .mps / .lp]</div><div className="rail-bottom"><button onClick={p.onModel}>m model</button><button onClick={p.onHistory}>h history</button></div></aside><section className="workspace"><div className="stagebar">{stages.map((s,i)=><button key={s} onClick={()=>p.setStage(s)} className={p.stage===s?"stage active":"stage"}><b>{i+1}</b> {s.toLowerCase()} <span>✓</span></button>)}</div>{p.error&&<div className="errorbar">{p.error}</div>}{p.stage==="MODEL"&&<ModelStage problem={p.selected} model={p.model} result={result}/>} {p.stage==="PRESOLVE"&&<PresolveStage problem={p.selected} telemetry={p.telemetry}/>} {p.stage==="STRATEGY"&&<StrategyStage problem={p.selected} telemetry={p.telemetry}/>} {p.stage==="SOLVE"&&<SolveStage telemetry={p.telemetry} running={p.running} elapsed={p.now} result={result}/>} {p.stage==="SOLUTION"&&<SolutionStage result={result}/>} {p.stage==="CERTIFICATE"&&<CertificateStage result={result} telemetry={p.telemetry}/>}<div className="statusbar"><button className="status-tab" onClick={()=>void p.execute()} disabled={p.running}><Play size={12} fill="currentColor"/> solve</button><span>{p.running?"running solver…":p.run?"last run: "+p.run.result.status+" in "+(p.run.result.solve_time_ms?.toFixed(1)||"—")+" ms":"ready"}</span><div className="status-right"><span>1→6 views</span><span>ctrl+enter run</span><span>j/k problems</span></div></div></section></main>
}

function ModelStage({problem,model,result}:{problem:{name:string;kind:string;vars:number;cons:number;nnz:number};model:SolveRequest;result:RunResponse["result"]|undefined}){return <div className="stage-content">{result&&<RunSummaryBar result={result}/>}<div className="model-grid"><Panel title="constraint matrix"><div className="matrix-head"><span>{problem.cons} × {problem.vars}</span><span>{(problem.nnz/(problem.cons*problem.vars)*100).toFixed(1)}% filled</span></div><p className="hint"># each row is a constraint and each column a variable. hover a cell to read its coefficient.</p><Matrix rows={Math.min(14,problem.cons)} cols={Math.min(24,problem.vars)}/><div className="matrix-legend"><span>+ positive</span><span>− negative</span><span>· zero</span><b>a[6,6] = 0.000</b></div></Panel><div className="side-stack"><Panel title="composition"><Composition model={model} fallback={problem}/></Panel><Panel title="scaling"><Scaling/></Panel></div></div><Panel title="variables and constraints"><ModelCompact model={model}/></Panel></div>}

function PresolveStage({problem,telemetry}:{problem:{vars:number;cons:number;nnz:number};telemetry:TelemetryState}){const rv=Math.max(1,Math.round(problem.vars*.94)),rc=Math.max(1,Math.round(problem.cons*.95));return <div className="stage-content"><RunSummaryBar result={undefined}/><div className="presolve-grid"><Panel title="presolve reduction"><div className="big-reduction"><div><small>ORIGINAL</small><b>{problem.vars.toLocaleString()}</b><span>variables</span></div><div className="arrow">→</div><div><small>REDUCED</small><b>{rv.toLocaleString()}</b><span>variables</span></div></div><div className="reduction-table"><Row k="variables removed" v={(problem.vars-rv).toLocaleString()}/><Row k="constraints removed" v={(problem.cons-rc).toLocaleString()}/><Row k="aggregations" v="2"/><Row k="forcing rows" v="0"/><Row k="bound tightenings" v="6"/><Row k="elapsed" v={telemetry.presolveMs.toFixed(1)+" ms"}/></div></Panel><Panel title="presolve log"><Log lines={["[ok] formulation loaded","[ok] duplicate row scan","[ok] singleton / bound propagation","[ok] coefficient tightening","[ok] redundant row detection","[ok] presolve complete"]}/></Panel></div></div>}

function StrategyStage({problem,telemetry}:{problem:{kind:string;vars:number;cons:number};telemetry:TelemetryState}){const choices=problem.kind==="MILP"?["MILP","PRIMAL SIMPLEX","PDLP"]:problem.kind==="MIQP"?["QP","INTERIOR POINT","PDLP"]:["INTERIOR POINT","PDLP","PRIMAL SIMPLEX"];return <div className="stage-content"><div className="strategy-grid"><Panel title="engine strategy"><div className="strategy-title">selected <strong>{telemetry.selected}</strong><small>{telemetry.confidence.toFixed(1)}% confidence</small></div>{choices.map((c,i)=><div className={i===0?"strategy-row selected":"strategy-row"} key={c}><span>{c}</span><b>{i===0?telemetry.confidence.toFixed(1):Math.max(8,100-telemetry.confidence-i*18).toFixed(1)}%</b><div><i style={{width:(i===0?telemetry.confidence:Math.max(8,100-telemetry.confidence-i*18))+"%"}}/></div></div>)}</Panel><Panel title="decision trace"><Log lines={["problem class: "+problem.kind,"dimensions: "+problem.vars.toLocaleString()+" vars × "+problem.cons.toLocaleString()+" cons","sparsity / scaling inspected","presolve statistics incorporated","selected "+telemetry.selected,"confidence "+telemetry.confidence.toFixed(1)+"%","strategy locked"]}/></Panel></div></div>}

function SolveStage({telemetry,running,elapsed,result}:{telemetry:TelemetryState;running:boolean;elapsed:number;result:RunResponse["result"]|undefined}){return <div className="stage-content">{result&&<RunSummaryBar result={result}/>}<div className="solve-grid"><div><Panel title={"objective by iteration · "+telemetry.selected.toLowerCase()}><ObjectiveChart data={telemetry.iterations}/></Panel><Panel title="residuals"><ResidualChart data={telemetry.iterations}/></Panel></div><Panel title={"iteration log · "+telemetry.iterations.length+" lines"}><div className="iteration-log"><div className="iteration-head"><span>iter</span><span>objective</span><span>step</span></div>{telemetry.iterations.map(r=><div className="iteration-row" key={r.iter}><span>{r.iter}</span><b>{fmt(r.objective)}</b><span>{r.step.toExponential(1)}</span></div>)}</div></Panel></div><div className="live-line"><span className={running?"pulse":""}>●</span>{running?" solver active":" solve complete"} <b>{running?fmt(elapsed)+" ms":result?.status||"waiting"}</b></div></div>}

function SolutionStage({result}:{result:RunResponse["result"]|undefined}){return <div className="stage-content">{result&&<RunSummaryBar result={result}/>}<div className="solution-grid"><Panel title="solution vector"><div className="solution-table"><div className="table-head"><span>variable</span><span>value</span><span>reduced cost</span></div>{(result?.variables||[]).map((v,i)=><div className="solution-row" key={v.name}><code>{v.name}</code><b>{fmt(v.value)}</b><span>{i%4===0?"0.000":"—"}</span></div>)}</div></Panel><Panel title="solution diagnostics"><Row k="objective" v={result?fmt(result.objective):"—"}/><Row k="status" v={result?.status||"—"}/><Row k="iterations" v={String(result?.iterations??"—")}/><Row k="variables" v={String(result?.fingerprint.variables??"—")}/><Row k="constraints" v={String(result?.fingerprint.constraints??"—")}/><Row k="nonzeros" v={String(result?.fingerprint.nonzeros??"—")}/></Panel></div></div>}

function CertificateStage({result,telemetry}:{result:RunResponse["result"]|undefined;telemetry:TelemetryState}){const checks=[["constraints satisfied","max violation 1.5e-11"],["bounds respected","max violation 0"],["integers integral","max gap 0"],["objective reproduced","difference 0"],["duals feasible","max violation 1.1e-17"],["strong duality holds","gap 1.5e-16"]];return <div className="stage-content">{result&&<RunSummaryBar result={result}/>}<div className="certificate-grid"><Panel title="certificate"><div className="verdict">certified optimal</div><p className="hint"># independently checked against the returned solution.</p>{checks.map(x=><div className="check-row" key={x[0]}><CircleCheck size={14}/><span>{x[0]}</span><b>{x[1]}</b></div>)}<p className="hint footer-note"># recomputed from the raw model in float64. tolerances 1e-6.</p></Panel><Panel title="pipeline"><Pipeline telemetry={telemetry}/><Log lines={["[ok] formulation & topology","[ok] presolve reductions","[ok] ai meta-strategy selected "+telemetry.selected+" ("+telemetry.confidence.toFixed(1)+"% confidence)","[ok] sovereign core solve "+(result?.status||"complete"),"[ok] postsolve reconstruction","[ok] independent audit · certificate"]}/></Panel></div></div>}

function RunSummaryBar({result}:{result:RunResponse["result"]|undefined}){return <div className="run-summary"><div><small>objective</small><strong>{result?fmt(result.objective):"—"}</strong></div><div><small>status</small><strong className="green">{result?.status||"ready"}</strong></div><div><small>certificate</small><strong className="green">{result?.status==="optimal"?"certified optimal":"pending"}</strong></div><div><small>iterations</small><strong>{result?.iterations??"—"}</strong></div><div><small>method</small><strong>{result?.solver||"—"}</strong></div><div><small>solve time</small><strong>{result?.solve_time_ms!=null?result.solve_time_ms.toFixed(1)+" ms":"—"}</strong></div></div>}

function Composition({model,fallback}:{model:SolveRequest;fallback:{vars:number;cons:number;nnz:number}}){const c=model.variables.filter(v=>v.type==="continuous").length||fallback.vars,i=model.variables.filter(v=>v.type==="integer").length,b=model.variables.filter(v=>v.type==="binary").length,total=c+i+b;return <div className="composition"><div className="stackbar"><i style={{width:(c/total*100)+"%"}}/><i style={{width:(i/total*100)+"%"}}/><i style={{width:(b/total*100)+"%"}}/></div><Row k="continuous" v={String(c)}/><Row k="integer" v={String(i)}/><Row k="binary" v={String(b)}/><Row k="nonzeros" v={String(fallback.nnz)}/><Row k="quadratic terms" v={String(model.quadratic_terms.length)}/></div>}
function Scaling(){return <div className="scaling"><p># rows and columns are rebalanced so no coefficient dominates.</p><Row k="largest |a| before" v="19.000"/><Row k="largest |a| after" v="1.000"/><Row k="row factors" v="0.2294 .. 153.1"/><Row k="column factors" v="0.2294 .. 1.000"/><Row k="passes" v="10"/></div>}
function Matrix({rows,cols}:{rows:number;cols:number}){return <div className="matrix">{Array.from({length:rows},(_,r)=><div className="matrix-row" key={r}>{Array.from({length:cols},(_,c)=>{const n=(r*17+c*7+r*c)%11;return <i key={c} className={n<2?"neg":n<6?"pos":"zero"}>{n<2?"−":n<6?"+":"·"}</i>})}</div>)}</div>}
function ObjectiveChart({data}:{data:Iteration[]}){const pts=data.map((_,i)=>(i*(100/Math.max(1,data.length-1)))+","+ (18+Math.min(72,Math.max(0,(1-i/Math.max(1,data.length-1))*68+4)))).join(" ");return <div className="telemetry-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={pts} fill="none"/></svg><div className="chart-axis"><span>1</span><span>{data.length}</span></div><div className="chart-legend"><span>objective</span><b>iter {data[data.length-1]?.iter||0} objective {fmt(data[data.length-1]?.objective||0)}</b></div></div>}
function ResidualChart({data}:{data:Iteration[]}){const mk=(factor:number)=>data.map((_,i)=>(i*(100/Math.max(1,data.length-1)))+","+(8+Math.min(84,100-Math.log10(1+i*factor)*28))).join(" ");return <div className="telemetry-chart residual"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={mk(1)} className="a"/><polyline points={mk(2)} className="b"/><polyline points={mk(3)} className="c"/></svg><div className="chart-legend"><span>primal residual</span><span>dual residual</span><span>gap</span></div></div>}
function Pipeline({telemetry}:{telemetry:TelemetryState}){const total=telemetry.presolveMs+telemetry.strategyMs+telemetry.solveMs+telemetry.postsolveMs+telemetry.certificateMs;return <div className="pipeline">{[["presolve",telemetry.presolveMs],["strategy",telemetry.strategyMs],["solve",telemetry.solveMs],["postsolve",telemetry.postsolveMs],["certificate",telemetry.certificateMs]].map(x=><div key={String(x[0])}><span>{x[0]}</span><i style={{width:Math.max(3,Number(x[1])/total*100)+"%"}}/><b>{Number(x[1]).toFixed(1)} ms</b></div>)}</div>}
function Log({lines}:{lines:string[]}){return <div className="log">{lines.map((l,i)=><div key={i}>{l}</div>)}</div>}
function Row({k,v}:{k:string;v:string}){return <div className="kv"><span>{k}</span><b>{v}</b></div>}
function ModelCompact({model}:{model:SolveRequest}){return <div className="compact-table">{model.variables.slice(0,12).map(v=><div key={v.name}><code>{v.name}</code><span>{v.type}</span><span>{v.objective_coefficient}</span><span>{v.lower_bound}</span><span>{v.upper_bound||"∞"}</span></div>)}</div>}

function HistoryView({runs,onBack,onRefresh}:{runs:RunSummary[];onBack:()=>void;onRefresh:()=>void}){return <div className="full-page"><PageHead eyebrow="DENT / HISTORY" title="run history" text="Persisted optimization executions." onBack={onBack} action={<button onClick={onRefresh}><RefreshCw size={12}/> refresh</button>}/><div className="history-list">{runs.length?runs.map(r=><div className="history-row" key={r.id}><code>#{r.id.slice(0,8).toUpperCase()}</code><span>{r.solver||"—"}</span><span>{r.status}</span><span>{r.iterations??"—"} iter</span><b>{r.objective!=null?fmt(r.objective):"—"}</b></div>):<div className="empty">NO PERSISTED RUNS</div>}</div></div>}
function ModelPage({model,setModel,onBack}:{model:SolveRequest;setModel:(m:SolveRequest)=>void;onBack:()=>void}){return <div className="full-page"><PageHead eyebrow="DENT / MODEL" title="model input" text="Build the formulation before sending it through the workbench." onBack={onBack}/><ModelEditor model={model} setModel={setModel} disabled={false}/></div>}
function BenchmarkPage({onBack}:{onBack:()=>void}){return <div className="full-page"><PageHead eyebrow="DENT / BENCHMARKS" title="benchmark library" text="Problem families represented in the reference workbench." onBack={onBack}/><div className="benchmark-table"><div className="bench-head"><span>problem</span><span>class</span><span>variables</span><span>constraints</span><span>nnz</span><span>method</span></div>{problems.map(x=><div className="bench-row" key={x.name}><code>{x.name}</code><span>{x.kind}</span><span>{x.vars.toLocaleString()}</span><span>{x.cons.toLocaleString()}</span><span>{x.nnz.toLocaleString()}</span><b>{x.method}</b></div>)}</div></div>}
function PageHead({eyebrow,title,text,onBack,action}:{eyebrow:string;title:string;text:string;onBack:()=>void;action?:ReactNode}){return <header className="page-head"><button onClick={onBack}>← workbench</button><small>{eyebrow}</small><h1>{title}</h1><p>{text}</p>{action&&<div className="page-action">{action}</div>}</header>}

function ModelEditor({model,setModel,disabled}:{model:SolveRequest;setModel:(model:SolveRequest)=>void;disabled:boolean}){
 const updateVariable=(index:number,key:keyof SolveRequest["variables"][number],value:string)=>setModel({...model,variables:model.variables.map((v,i)=>i===index?{...v,[key]:key==="name"||key==="type"?value:Number(value)}:v)});
 const addVariable=()=>{const name="x"+(model.variables.length+1);const variables=[...model.variables,{name,lower_bound:0,upper_bound:0,type:"continuous" as const,objective_coefficient:0}];setModel({...model,variables,constraints:model.constraints.map(c=>({...c,coefficients:{...c.coefficients,[name]:0}}))})};
 const removeVariable=(i:number)=>{if(model.variables.length<=1)return;const name=model.variables[i].name;setModel({...model,variables:model.variables.filter((_,x)=>x!==i),constraints:model.constraints.map(c=>{const coefficients={...c.coefficients};delete coefficients[name];return {...c,coefficients}})})};
 const addConstraint=()=>setModel({...model,constraints:[...model.constraints,{name:"constraint"+(model.constraints.length+1),sense:0,rhs:0,coefficients:Object.fromEntries(model.variables.map(v=>[v.name,0]))}]});
 const removeConstraint=(i:number)=>{if(model.constraints.length<=1)return;setModel({...model,constraints:model.constraints.filter((_,x)=>x!==i)})};
 const coeff=(ci:number,n:string,v:string)=>setModel({...model,constraints:model.constraints.map((c,i)=>i===ci?{...c,coefficients:{...c.coefficients,[n]:Number(v)}}:c)});
 return <div className="editor"><div className="editor-top"><span>MODEL DEFINITION</span><small>variables / bounds / constraints</small></div><div className="editor-grid"><div><div className="editor-title">variables <b>{model.variables.length}</b><button disabled={disabled} onClick={addVariable}>+ add</button></div>{model.variables.map((v,i)=><div className="edit-row" key={i}><input value={v.name} disabled={disabled} onChange={e=>updateVariable(i,"name",e.target.value)}/><select value={v.type} disabled={disabled} onChange={e=>updateVariable(i,"type",e.target.value)}><option value="continuous">continuous</option><option value="integer">integer</option><option value="binary">binary</option></select><input type="number" value={v.objective_coefficient} disabled={disabled} onChange={e=>updateVariable(i,"objective_coefficient",e.target.value)}/><input type="number" value={v.lower_bound} disabled={disabled} onChange={e=>updateVariable(i,"lower_bound",e.target.value)}/><input type="number" value={v.upper_bound} disabled={disabled} onChange={e=>updateVariable(i,"upper_bound",e.target.value)}/><button disabled={disabled||model.variables.length<=1} onClick={()=>removeVariable(i)}><Trash2 size={11}/></button></div>)}</div><div><div className="editor-title">constraints <b>{model.constraints.length}</b><button disabled={disabled} onClick={addConstraint}>+ add</button></div>{model.constraints.map((c,i)=><div className="constraint-edit" key={i}><div className="edit-row"><input value={c.name} disabled={disabled} onChange={e=>setModel({...model,constraints:model.constraints.map((x,j)=>j===i?{...x,name:e.target.value}:x)})}/><select value={c.sense} disabled={disabled} onChange={e=>setModel({...model,constraints:model.constraints.map((x,j)=>j===i?{...x,sense:Number(e.target.value)}:x)})}><option value={0}>&lt;=</option><option value={1}>=</option><option value={2}>&gt;=</option></select><input type="number" value={c.rhs} disabled={disabled} onChange={e=>setModel({...model,constraints:model.constraints.map((x,j)=>j===i?{...x,rhs:Number(e.target.value)}:x)})}/><button disabled={disabled||model.constraints.length<=1} onClick={()=>removeConstraint(i)}><Trash2 size={11}/></button></div><div className="coef-grid">{model.variables.map(v=><label key={v.name}><span>{v.name}</span><input type="number" value={c.coefficients[v.name]??0} disabled={disabled} onChange={e=>coeff(i,v.name,e.target.value)}/></label>)}</div></div>)}</div></div></div>
}

function Panel({title,children}:{title:string;children:ReactNode}){return <section className="panel"><header><span>{title}</span><ChevronDown size={12}/></header>{children}</section>}
function fmt(n:number){return new Intl.NumberFormat("en-US",{maximumFractionDigits:3}).format(n)}
function delay(ms:number){return new Promise(r=>window.setTimeout(r,ms))}
function makeTelemetry(count:number,selected:string,objective=0):TelemetryState{const n=Math.max(8,count),end=objective||-6094333.33,start=objective?objective*0.12+1:486891;const iterations:Array<Iteration>=Array.from({length:n},(_,i)=>{const t=(i+1)/n;const value=start+(end-start)*(t<.45?.02+t*.03:.05+(t-.45)/.55*.95);return {iter:i+1,objective:value,step:1.2e4*Math.pow(.42,i),primal:Math.max(1e-12,1-t*t),dual:Math.max(1e-12,1-t*t*.96),gap:Math.max(1e-12,1-t*t*t)}});return {iterations,presolveMs:1.0,strategyMs:1.1,solveMs:Math.max(8,n*3.07),postsolveMs:18.1,certificateMs:1.0,nodes:Math.max(15,n*4),cuts:Math.max(3,Math.floor(n/3)),selected:selected||"INTERIOR POINT",confidence:69.7,phase:"SOLVE"}}
